// Generated by the Waffle++ code generator. DO NOT EDIT!
// source: employee.h

#include <waffle/modules/rest_controller/rest_controller.h>

#include "employee.h"

namespace Waffle {

namespace Impl {

} // namespace Impl

template<>
HttpResponse ProcessRequest(model::EmployeeController& handler, const HttpRequest& httpRequest) {
    return {};
}

} // namespace Waffle
