// Generated by the Waffle++ code generator. DO NOT EDIT!
// source: misc_enum_places.h

#include <stdexcept>
#include <waffle/modules/enum_serializer/enum_serializer.h>
#include </home/izaron/WafflePlusPlus/build/modules/enum_serializer/test/misc_enum_places/misc_enum_places.h>

namespace Waffle {

template<>
Color FromString<Color>(std::string_view value) {
    if (value == "Red") {
        return Color::Red;
    }
    if (value == "Green") {
        return Color::Green;
    }
    if (value == "Blue") {
        return Color::Blue;
    }
    if (value == "Cyan") {
        return Color::Cyan;
    }
    if (value == "Magenta") {
        return Color::Magenta;
    }
    if (value == "Yellow") {
        return Color::Yellow;
    }
    if (value == "Black") {
        return Color::Black;
    }
    throw std::runtime_error("Can't parse value \"" + std::string{value} + "\" to enum type \"Color\"");
}

template<>
OsManager::Type FromString<OsManager::Type>(std::string_view value) {
    if (value == "LINUX") {
        return OsManager::LINUX;
    }
    if (value == "WINDOWS") {
        return OsManager::WINDOWS;
    }
    if (value == "OSX") {
        return OsManager::OSX;
    }
    throw std::runtime_error("Can't parse value \"" + std::string{value} + "\" to enum type \"OsManager::Type\"");
}

template<>
The::Longest::Namespace::Very::Long::Qualified::Name::Value FromString<The::Longest::Namespace::Very::Long::Qualified::Name::Value>(std::string_view value) {
    if (value == "Foo") {
        return The::Longest::Namespace::Very::Long::Qualified::Name::Value::Foo;
    }
    throw std::runtime_error("Can't parse value \"" + std::string{value} + "\" to enum type \"The::Longest::Namespace::Very::Long::Qualified::Name::Value\"");
}

} // namespace Waffle
