// Generated by the Waffle++ code generator. DO NOT EDIT!
// source: misc_enum_places.h

int kek = 1337;
// values for Color
// Color::Red <---> red
// Color::Red <---> rote
// Color::Green <---> green
// Color::Blue <---> blue
// values for OsManager::Type
// OsManager::LINUX <---> LINUX
// OsManager::WINDOWS <---> WINDOWS
// OsManager::OSX <---> OSX
