// Generated by the Waffle++ code generator. DO NOT EDIT!
// source: structs.h

#include "structs.h"

namespace Waffle {

// Please implement Robot
// Please implement Stringer

} // namespace Waffle
