// Generated by the Waffle++ code generator. DO NOT EDIT!
// source: counter.h

#include <waffle/modules/signals/signals.h>

#include "counter.h"

namespace Waffle {

inline SignalBase::~SignalBase() {
}

// ???

} // namespace Waffle
