// Generated by the Waffle++ code generator. DO NOT EDIT!
// source: simple_structs.h

#include <sstream>

#include <waffle/modules/dump_struct/dump_struct.h>

#include "simple_structs.h"

namespace Waffle {

template<>
std::string DumpStruct(const Test0& value) {
    std::stringstream ss;
    return ss.str();
}

template<>
std::string DumpStruct(const Test1& value) {
    std::stringstream ss;
    ss << "aaa = " << value.aaa << "\n";
    ss << "bbb = " << value.bbb << "\n";
    ss << "ccc = " << value.ccc << "\n";
    ss << "ddd = " << value.ddd << "\n";
    ss << "eee = " << value.eee << "\n";
    return ss.str();
}

} // namespace Waffle
