// Generated by the Waffle++ code generator. DO NOT EDIT!
// source: {{ source_file }}

#include <sstream>

#include <waffle/modules/dump_struct/dump_struct.h>

#include "{{ source_file }}"

namespace Waffle {

## for struct in structs
template<>
std::string DumpStruct(const {{ struct.name }}& value) {
    std::stringstream ss;
## for line in struct.lines
    ss << "{{ indent(length(line.path) - 1) }}{{ last(line.path) }} = ";
{% if line.type == "simple" %}
    ss << value.{{ join(line.path, ".") }};
{% else if line.type == "string" %}
    ss << "\"" << value.{{ join(line.path, ".") }} << "\"";
{% else if line.type == "struct" %}
    ss << "{{ line.struct_name }}";
{% endif %}
    ss << "\n";

## endfor
    return ss.str();
}

## endfor
} // namespace Waffle
