// Generated by the Waffle++ code generator. DO NOT EDIT!
// source: turtle.h

#include <gmock/gmock.h>

#include "turtle.h"

namespace Waffle {

class MockTurtle : public model::Turtle {
public:
    MOCK_METHOD(void, PenUp, (), (override));
    MOCK_METHOD(void, PenDown, (), (override));
    MOCK_METHOD(void, Forward, (int distance), (override));
    MOCK_METHOD(void, Turn, (int degrees), (override));
    MOCK_METHOD(void, GoTo, (int x, int y), (override));
    MOCK_METHOD(int, GetX, (), (const, override));
    MOCK_METHOD(int, GetY, (), (const, override));
};

} // namespace Waffle
