// Generated by the Waffle++ code generator. DO NOT EDIT!
// source: comment_styles.cpp
int kek = 1337;
// values for EColored
// Red <---> dummy
// Green <---> dummy
// Blue <---> dummy
// values for EColor2
// EColor2::Red <---> dummy
// EColor2::Green <---> dummy
// EColor2::Blue <---> dummy
// values for OsManager::Type
// OsManager::LINUX <---> dummy
// OsManager::WINDOWS <---> dummy
// OsManager::OSX <---> dummy
