// Generated by the Waffle++ code generator. DO NOT EDIT!
// source: comment_styles.cpp
int kek = 1337;
// values for EColored
// Red <---> red
// Red <---> rote
// Green <---> green
// Blue <---> blue
// values for EColor2
// EColor2::Red <---> red
// EColor2::Green <---> green
// EColor2::Blue <---> blue
// values for OsManager::Type
// OsManager::LINUX <---> LINUX
// OsManager::WINDOWS <---> WINDOWS
// OsManager::OSX <---> OSX
