// Generated by the Waffle++ code generator. DO NOT EDIT!
// source: /home/izaron/WafflePlusPlus/src/modules/enum_serializer/test/comment_styles/comment_styles.cpp
int kek = 1337;
// EColored
// EColor2
// OsManager::Type
