// Generated by the Waffle++ code generator. DO NOT EDIT!
// source: {{ source_file }}

#include <vector>
#include <stdexcept>

#include <waffle/modules/enum_serializer/enum_serializer.h>

#include "{{ source_file }}"

namespace Waffle {

} // namespace Waffle
