// Generated by the Waffle++ code generator. DO NOT EDIT!
// source: {{ source_file }}

#include <waffle/modules/signals/signals.h>

#include "{{ source_file }}"

namespace Waffle {

inline SignalBase::~SignalBase() {
}

// ???

} // namespace Waffle
## for struct in structs
## for signal in struct.signals

void {{ struct.qualified_name }}::{{ signal.name }}({{ signal.signature }}) {
}
## endfor
## endfor
