// Generated by the Waffle++ code generator. DO NOT EDIT!
// source: {{ source_file }}

#include <waffle/modules/signals/signals.h>

#include "{{ source_file }}"

namespace Waffle {

inline SignalBase::~SignalBase() {
}

// ???

} // namespace Waffle
